# Generated by Django 5.1.1 on 2024-09-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_desc', models.CharField(max_length=30)),
                ('item_price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='image/')),
                ('itam_resume', models.FileField(upload_to='file/')),
            ],
        ),
    ]
